### ISSUE TITLE
Query parsing doesn't work right with some words

### ISSUE THREAD

**Issue by dphaener** [EditLLC/ruby-montage#20]
Words that have "in" in them. For instance: "name ilike 'kings'" parses to {:filter=>{:"name ilike 'k__in"=>"g"}

**Comment by zackify** [comment]
good catch

**Comment by dphaener** [comment]
Was quite the accident actually. Searching for kings county on water where....

**Comment by zackify** [comment]
would it be as easy as adding a space here https://github.com/EditLLC/ruby-montage/blob/master/lib/montage/operators/in.rb#L5 and the other ones
